version: '2'
services:
  python:
    image: nariyadav/docker:2.0
    container_name: python
    environment:
      - "redis_host=redis"
    ports:
     - "8080:5000"
    networks:
      - nariyadav
  redis:
    container_name: redis
    image: "redis"
    networks:
      - nariyadav
networks:
  javahome-app:
    driver: bridge
